language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install git+https://github.com/lux-org/lux-widget
# command to run tests
script:
  - black --target-version py37 --check .
  - python -m pytest tests/*.py
  - pytest --cov-report term --cov=lux tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)
